"use client";

import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import localFont from "next/font/local";
import { Icons } from "@/components/Icons";
import { NavItem } from "@/types";
import { buttonVariants } from "@/components/ui/button";
import Link from "next/link";
import Footer from "@/components/Footer";
import { ThemeProvider } from "next-themes";
import { Toaster } from "react-hot-toast";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});
const fontHeading = localFont({
  src: "../../public/CalSans-SemiBold.woff2",
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "GroVr-test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const items: NavItem[] = [
    {
      title: "Features",
      href: "/#features",
    },
    {
      title: "Pricing",
      href: "/#pricing",
    },
    {
      title: "Blog",
      href: "https://yaoeb.vercel.app/",
    },
  ];

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-sans antialiased",
          fontSans.variable,
          fontHeading.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex min-h-screen flex-col">
            <header className="p-3 z-40 bg-background">
              <div className="flex h-20 items-center justify-between py-6">
                <Navbar items={items} />
                <nav>
                  <Link
                    href="/waitlist"
                    className={cn(buttonVariants({ size: "sm" }), "px-4")}
                  >
                    Join Waitlist!
                  </Link>
                </nav>
              </div>
            </header>
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
